# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='NIP',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='agama',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
