# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_kecerdasan'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasaKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'masakerja',
                'ordering': ['id'],
            },
        ),
    ]
