# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0005_masakerja_lima_delapanthn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masakerja',
            old_name='lima_delapanthn',
            new_name='lima_sd_delapan',
        ),
    ]
