# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_auto_20180726_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masakerja',
            old_name='test',
            new_name='nol_sd_empat',
        ),
    ]
