# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_auto_20180726_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='masakerja',
            name='dualima_sd_duadelapan',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='masakerja',
            name='duasatu_sd_duaempat',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='masakerja',
            name='duasembilan_sd_tigadua',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='masakerja',
            name='sembilan_sd_tigaenam',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='masakerja',
            name='tigabelas_sd_enambelas',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='masakerja',
            name='tigatiga_sd_tigaenam',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='masakerja',
            name='tujuhbelas_sd_duapuluh',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
