# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_auto_20180726_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendidikanTerakhir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SD', models.IntegerField(blank=True, max_length=5, null=True)),
                ('SMP', models.IntegerField(blank=True, max_length=5, null=True)),
                ('SMA', models.IntegerField(blank=True, max_length=5, null=True)),
                ('DIII', models.IntegerField(blank=True, max_length=5, null=True)),
                ('Strata_satu', models.IntegerField(blank=True, max_length=5, null=True)),
                ('Strata_dua', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'pendidikanterakhir',
                'ordering': ['id'],
            },
        ),
    ]
