# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0009_pendidikanterakhir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prilaku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominance', models.IntegerField(blank=True, max_length=5, null=True)),
                ('influences', models.IntegerField(blank=True, max_length=5, null=True)),
                ('steadines', models.IntegerField(blank=True, max_length=5, null=True)),
                ('compliance', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'prilaku',
                'ordering': ['id'],
            },
        ),
    ]
