# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_prilaku'),
    ]

    operations = [
        migrations.CreateModel(
            name='SikapKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energi_psikis', models.IntegerField(blank=True, max_length=5, null=True)),
                ('ketelitian', models.IntegerField(blank=True, max_length=5, null=True)),
                ('kehati_hatian', models.IntegerField(blank=True, max_length=5, null=True)),
                ('pengendalian_prasaan', models.IntegerField(blank=True, max_length=5, null=True)),
                ('dorongan_berprestasi', models.IntegerField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'sikapkerja',
                'ordering': ['id'],
            },
        ),
    ]
