# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0012_auto_20180726_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecerdasan',
            name='sistematika_berfikir',
            field=models.CharField(max_length=5),
        ),
    ]
