# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0013_auto_20180726_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='NIP',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
