# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0016_karyawan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kecerdasan',
            name='karyawan',
        ),
        migrations.AddField(
            model_name='kecerdasan',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
