# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0017_auto_20180726_1511'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kecerdasan',
            table='nama',
        ),
    ]
