# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0020_auto_20180726_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'province',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='karyawan',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawans', to='orm.Province'),
        ),
    ]
