# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-26 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0026_auto_20180726_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='masakerja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawans', to='orm.MasaKerja'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='pendidikanterakhir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawans', to='orm.PendidikanTerakhir'),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='prilaku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawans', to='orm.Prilaku'),
        ),
        migrations.AlterField(
            model_name='masakerja',
            name='nol_sd_empat',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pendidikanterakhir',
            name='SD',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='prilaku',
            name='dominance',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
