# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-01 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0028_auto_20180727_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecerdasan',
            name='karyawan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kecerdasans', to='orm.Karyawan'),
        ),
        migrations.AlterField(
            model_name='masakerja',
            name='karyawan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masakerjas', to='orm.Karyawan'),
        ),
        migrations.AlterField(
            model_name='pendidikanterakhir',
            name='karyawan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendidikanterkahirs', to='orm.Karyawan'),
        ),
        migrations.AlterField(
            model_name='prilaku',
            name='karyawan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prilakus', to='orm.Karyawan'),
        ),
        migrations.AlterField(
            model_name='sikapkerja',
            name='karyawan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sikapkerjas', to='orm.Karyawan'),
        ),
    ]
