# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-01 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0029_auto_20180801_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendidikanterakhir',
            name='karyawan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendidikanterakhirs', to='orm.Karyawan'),
        ),
    ]
